login:
    api_key: futural
    api_secret: ***REMOVED***
    app_id: 6202029
    app_key: dc59e51b4cdf4687b27154e159c49d8d

schema:
    title: text
    sa-har-ser-jag-ut: image
    personnummer-2: text
    kon: category
    sektion-2: category
    category: category
#   sektion: text
    post-2: category
    post: text
    mobilnummer-2: text
    vad-tillhor-du: category
    mail: text
    alternativ-mailadress: text
    mobilnummer-2: text
    adress: text
    postnummer-och-ort: text
    matpreferenser: text
    trojstorlek: category
    fatt-karnevalsmail: category
    fatt-valkomstmail: category
